export { IApiConfig, CPWXCoreFactory, CPWXCore } from './src/CPWXCore'

export { DepartmentAPI } from './src/api/DepartmentAPI'
export { TagAPI } from './src/api/TagAPI'
export { UserAPI } from './src/api/UserAPI'
export { UserSyncAPI, ISyncCallback } from './src/api/UserSyncAPI'
export { ExContactAPI } from './src/api/ExContactAPI'
export { OauthAPI } from './src/api/OauthAPI'
export { AgentAPI } from './src/api/AgentAPI'
export { OADataAPI } from './src/api/OADataAPI'
export { CalendarAPI } from './src/api/CalendarAPI'
export { WeDriveAPI } from './src/api/WeDriveAPI'
export { MeetingRoomAPI } from './src/api/MeetingRoomAPI'
export { InvoiceAPI } from './src/api/InvoiceAPI'
export { MediaAPI } from './src/api/MediaAPI'
export { GroupRobotAPI } from './src/api/GroupRobotAPI'
export { SendMsgAPI } from './src/api/SendMsgAPI'
export { ChatAPI } from './src/api/ChatAPI'

export { BaseMsg } from './src/entity/BaseMsg'
export { ImageMsg, Image } from './src/entity/ImageMsg'
export { MarkDownMsg } from './src/entity/MarkDownMsg'
export { NewsMsg, Articles, News } from './src/entity/NewsMsg'
export { TextMsg, Text } from './src/entity/TextMsg'
export { FileMsg } from './src/entity/FileMsg'
export { VideoMsg, Video } from './src/entity/VideoMsg'
export { VoiceMsg } from './src/entity/VoiceMsg'
export { TextCardMsg, TextCard } from './src/entity/TextCardMsg'
export { MpNewsMsg, MpNewsArticles, MpNews } from './src/entity/MpNewsMsg'
export { TaskCardMsg, TaskCard, TaskCardBtn } from './src/entity/TaskCardMsg'
export { MediaId } from './src/entity/MediaId'

export { SYSTEM_AGENT_ID, MediaType, MessageType } from './src/Enums'
